name: digia_engage
description: Flutter SDK for rendering server-driven UIs using JSON from Digia
  Studio. Supports dynamic layouts, state, actions, and custom widgets.
version: 1.4.0
repository: https://github.com/Digia-Technology-Private-Limited/digia_engage.git
homepage: https://digia.tech
documentation: https://docs.digia.tech
issue_tracker: https://github.com/Digia-Technology-Private-Limited/digia_engage/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

scripts:
  i: flutter pub get
  format: dart format .
  fix: dart fix --apply
  lint: derry fix; derry format
  analyze: dart analyze
  analyse: derry analyze

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  chewie: ^1.12.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  package_info_plus: ^8.3.1
  device_info_plus: ^10.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  video_player: ^2.10.0
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  derry: ^1.5.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
